export const movies =[
    {   id:1,
        title:"Avengers Endgame",
        plot:"Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.",
        price:199,
        rating:8.4,
        stars:0,
        poster:"https://www.movieposters.com/cdn/shop/products/108b520c55e3c9760f77a06110d6a73b_500x.jpg?v=1573652543",
        fav:true,
        kart:true,
    },
    {
        id:2,
        title:"wolf of the wall street",
        plot:"In 1987, Jordan Belfort (Leonardo DiCaprio) takes an entry-level job at a Wall Street brokerage firm. By the early 1990s, while still in his 20s, Belfort founds his own firm, Stratton Oakmont. Together with his trusted lieutenant (Jonah Hill) and a merry band of brokers, Belfort makes a huge fortune by defrauding wealthy investors out of millions.",
        price:99,
        rating:8.4,
        poster:"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRZGAw5morH2uLBVRf7YmocGr-eBl98e5KWyUmkJw5E2mSZHoXs" , 
        stars:0,
        fav:true,
        kart:true,
    },
    {
        id:3,
        title:"The Perks of Being a Wallflower",
        plot:"Socially awkward teen Charlie (Logan Lerman) is a wallflower, always watching life from the sidelines, until two charismatic students become his mentors. Free-spirited Sam (Emma Watson) and her stepbrother Patrick (Ezra Miller) help Charlie discover the joys of friendship, first love, music and more, while a teacher sparks Charlie's dreams of becoming a writer. ",
        price:399,
        rating:5.9,
        poster:"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTc-xATuBZZ6KkcQMh-0-HLs3O7SqV5m6a7lVotJOvMlKds3Qx3" , 
        stars:0,
        fav:true,
        kart:true,
    }
]